### ISSUE TITLE
Remaining TODOs

### ISSUE THREAD

**Issue by nightire** [choice-form/bts-reports#1]
- [x] 切换语言时改变 `html[lang]`
- [x] Image Modal Heading I18n
- [x] Funnel Grid 增加 `.funnel-bar[data-state="n"]`
- [x] Funnel Grid 列过滤显示
- [x] 在任何情况下都不保留 brand filters 的结果
- [x] Funnel Grid 支持品牌过滤
- [x] Funnel Grid 数据下载（XLSX/PDF）
- [x] 优化 intro.js
- [x] Subject FIlters 在选中项 >= 1 的时候就要开始筛选（之前是 >= 2 才开始）
- [x] `progress-ring` 抽取 i18n 前缀
- [x] Card 转换图片下载
- [x] 雷达图 tooltip 的文字 undefined
- [x] funnel-grid 净推荐值加 %
- [x] 总体评价 调到 购买触动力 的后/右边
- [x] 品牌传播力/购买触动力特殊化（+ class）
- [x] funnel-grid 增加每列的平均值
- [x] 检查移动端的下载功能
- [x] 检查移动端指标的文字说明
- [x] 对于空数据的处理（显示为空的卡片）
- [x] Global filter 增加年龄 |> see #2 
- [x] filter 为 0 时恢复所有 subjects |> see #2 
- [x] Global filter 增加一级菜单形式 |> see #2 
- [x] cards 的顺序和 display filter 同步 |> see #2 
- [x] bi-partite 图表和 `categoryType` 同步 |> see #2 
- [x] 云词下载成图片
- [x] 单一 Brand 或 Model 可以多卡片显示某维度全数据
- [x] 每个卡片增加一个当前数据量的数字（少于100红色警示）
- [x] index 上的项目名称 i18n
- [x] index 上的项目日期下拉选择
- [x] Grid 加上平均值的一行
- [x] Grid 下载 Excel 保留数据的单位
- [x] model 的 subject 增加对 segment 和 brand 的关系关联，display filter 支持 or 关系选择
- [x] ui-nav-item 组件更新

---

- [ ] 增加 Notification bar
- [ ] 支持卡片合并，并支持评论，写备注
- [ ] wijmo-grid 打乱维度排序（需要调研可行性）
- [ ] 为词云增加 Treemap Chart（需要 API 提供关联的原始词汇及其数量）
- [ ] 增加 guest 账号（客户端模拟）并限制只能访问 demo projects（供通用之外的用户）
